version: 2.1

commands:
  install_doppler_cli_local:
    steps:
      - run:
          name: Install Doppler CLI
          command: (curl -Ls https://cli.doppler.com/install.sh || wget -qO- https://cli.doppler.com/install.sh) | sh -s -- --no-install --no-package-manager
      - run:
          name: Verify installation
          command: ./doppler --version

  install_doppler_cli_system:
    steps:
      - run:
          name: Install Doppler CLI
          command: (curl -Ls https://cli.doppler.com/install.sh || wget -qO- https://cli.doppler.com/install.sh) | sh
      - run:
          name: Verify installation
          command: doppler --version

jobs:
  # If using machine executor, you will most likely need to install and use the Doppler binary locally due to system restrictions
  doppler_machine:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install Doppler CLI
          command: (curl -Ls https://cli.doppler.com/install.sh || wget -qO- https://cli.doppler.com/install.sh) | sh -s -- --no-install --no-package-manager
      - run:
          name: Test Doppler secrets access
          command: ./doppler run -- printenv | grep DOPPLER # Only used for testing purposes. Never do this!

  # Whether or not you'll be able to install the Doppler CLI using the standard install script will depend upon the image used
  doppler_docker:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Install Doppler CLI
          command: (curl -Ls https://cli.doppler.com/install.sh || wget -qO- https://cli.doppler.com/install.sh) | sh
      - run:
          name: Test Doppler secrets access
          command: doppler run -- printenv | grep DOPPLER # Only used for testing purposes. Never do this!

workflows:
  version: 2
  doppler_cli_test:
    jobs:
      - doppler_machine
      - doppler_docker
